### ISSUE TITLE
Opening some CDP files give "overflow of an arithmetic operation" error

### ISSUE THREAD

**Issue by ricomon35** [SilverGreen93/CDPExplorer#2]
Hi: I'm having issues as well. I have 2 cdp files at 2 gigs size each, and 1 cdp file at 3 gigs size. All 3 files throw the "overflow of an arithmetic operation" error when opening from the file menu, and only open showing a very small portion of the total archive. I can extract what I see in the window, w/o problems. 

Here are the links to each archive file >

content-archive1Rico - 3 gigs
https://drive.google.com/open?id=0B1b_ZNL7nlFVOWFNMjlSdDktLTQ

content-archive2Rico - 2 gigs
https://drive.google.com/open?id=0B1b_ZNL7nlFVZDBGcS1yd0lPcEU

content-archive3 - 2 gigs
https://drive.google.com/open?id=0B1b_ZNL7nlFVTVg0Z0syMmZqWHc

**Comment by SilverGreen93** [comment]
Verified issue: OK. It reproduces.

**Comment by SilverGreen93** [comment]
Issue fixed. Can you please try the build below and valitate if this does not reproduce anymore?
https://1drv.ms/u/s!Ano7p-K16N1oidEhFmDpZFWUHpHoEA?e=dC8cqq

**Comment by ricomon35** [comment]
I opened bot of my big CDPs, 2.45gigs, and 3.29gigs.
No opening errors, app shows all CDP'd kuids.
Both sets extracted successfully > select all, right clik, extract as CDP.
Both extracted kuid sets installed into TRS 2019 no errors, just the normal warning for older pre TRS 2019 content.

**Comment by SilverGreen93** [comment]
Ok, thanks for letting me know. I will officially release it.
