### ISSUE TITLE
How do I export the files in CDP explorer?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [SilverGreen93/CDPExplorer#5]
I am trying to get models from trainz, and using cdp explorer all I see is a list of files and not anything useful. How do I export these?

I know I do not seem native to this language here, my native language is English. But the "help" link told me to go here and it seems to be related to the cdp explorer.

**Comment by SilverGreen93** [comment]
You can save individual assets as CDP files by using the Asset menu -> Export as CDP, or by right clicking an asset in the list and selecting Export as CDP.
CDP Explorer cannot extract individual files from CDPs, just the assets.

**Comment by umustbeloggedintododat** [comment]
Oh, well thanks for the program.
